### ISSUE TITLE
Big list of todos

### ISSUE THREAD

**Issue by danburzo** [madeincluj/madeincluj#2]
# harti istorice 
- [ ] dacian/agnes to pick and stitch 1941 map
- [ ] warp and tiles for 1941 map
- [x] slider for map transparency: functionality
- [ ] slider for map transparency: design
- [x] toggle time period
- [x] load images in s3 bucket
# street names
- [ ] projection
- [x] json to html -> generate static pages for streets
- [ ] popup template for street
- [ ] dacian to make design
- [ ] load images in s3 bucket
# 3d buildings
- [x] .3ds to .obj
- [x] load .obj in three.js
# cladiri socialiste 
- [x] geojson for building: lat/long, properties: name, id (osm building id - repo madeincluj, geojson with buildings)
- [x] yaml metadata for building: id, name, description, array of picture ids
- [ ] yaml metadata for pictures: id, name, url
- [x] yaml to json
- [ ] json to html
- [x] load photomarkers based on json
- [ ] collect text from pictures
- [ ] load images in s3 bucket
# instagram
- [x] show/hide instagram layer
- [ ] low priority: scrape high res images from instagram api
# other
- [ ] google maps print at high resolution
- [ ] implement design
- [ ] pagina de about project
- [ ] include AFCN & OAR logo
- [ ] low priority: search feature
- [ ] integrate all layers
# future
- [ ] create scripts to upload data in S3 bucket
- [ ] mapwarper is open source. maybe fork it to create own version
- [ ] instagram API allows 5000 requests/hour/access_token - remember this if madeincluj becomes famous.

**Comment by cronco** [comment]
Just noticed indentation with tabs, will change settings from now on, sorry for your OCD.

**Comment by danburzo** [comment]
huh?
