### ISSUE TITLE
3D Buildings

### ISSUE THREAD

**Issue by danburzo** [madeincluj/madeincluj#5]
# Content
- Export all 3DS modules to .OBJ
- Upload gzipped OBJs to S3
# MIC.3DBuildings
- [x] Detect WebGL capability and show link in menu
- [x] Initialize 3D Buildings (separate page?)
- [x] Add first-person camera w/ keyboard/mouse movement
- [x] Add F[1..5] to maquette.
- [x] Add loader
- [x] Add earth plaque
- [ ] Don't allow camera to pass through earth
- [ ] Textures maybe?
- [x] Cluj fog?

**Comment by danburzo** [comment]
- [ ] Collision detection

**Comment by cronco** [comment]
A big maybe on collision detection.

Totally doable, just don't know if efficiently enough to let the page be usable.

**Comment by cronco** [comment]
Also problematic - we have no way of knowing when the scene is fully rendered. Three.js emits no such event, nor is there any other way I can tell...

We'll only be able to use the loader for the Ajax Req + a predefined timeout, maybe?

**Comment by cronco** [comment]
Possibly BRILLIANT IDEA -  on load, I set the camera looking vaguely down.

Then, if my theory is correct, I can do a collision detect which will return false untill the object is added to the scene.

**Comment by cronco** [comment]
Scratch that... LoadingManager is asynchronous, of course. 

Added `removeLoading()` to callback.

**Comment by cronco** [comment]
- [x] "take me home" button

**Comment by cronco** [comment]
I guess this, as a feature bug, can be closed.
